apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-service
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: hello-kubernetes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
