jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}", "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}", "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}", "tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init and Apply
      run: |
        terraform init
        terraform apply -auto-approve
    - name: Deploy Kubernetes Manifests
      run: |
        kubectl apply -f namespace.yaml
        kubectl apply -f deployment.yaml