name: Deploy AKS Cluster
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init and Apply
      run: |
        terraform init
        terraform apply -auto-approve
    - name: Deploy Kubernetes Manifests
      run: |
        kubectl apply -f namespace.yaml
        kubectl apply -f deployment.yaml
